version: '3'
services:
  standalone-branch:
    build:
      context: .
      dockerfile: docker/Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    image: cassproject/cass:${branch}
  standalone-version:
    build:
      context: .
      dockerfile: docker/Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    image: cassproject/cass:${version}
  node-branch:
    build:
      context: .
      dockerfile: docker/standalone/node/Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    image: cassproject/cass:node-${branch}
  node-version:
    build:
      context: .
      dockerfile: docker/standalone/node/Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    image: cassproject/cass:node-${version}
  alpine-branch:
    build:
      context: .
      dockerfile: docker/standalone/node/DockerfileAlpine
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    image: cassproject/cass:node-${branch}-alpine
  alpine-version:
    build:
      context: .
      dockerfile: docker/standalone/node/DockerfileAlpine
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    image: cassproject/cass:node-${version}-alpine
  distroless-branch:
    build:
      context: .
      dockerfile: docker/standalone/node/DockerfileDistroless
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    image: cassproject/cass:node-${branch}-distroless
  distroless-version:
    build:
      context: .
      dockerfile: docker/standalone/node/DockerfileDistroless
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    image: cassproject/cass:node-${version}-distroless