/**
 * HTTP client for proxying MCP tool calls to the CaSS REST API.
 *
 * Uses the Node.js built-in global `fetch` (available in Node 18+).
 * Handles path parameter substitution, query string construction,
 * and JSON request/response body handling.
 *
 * CaSS uses signature sheets for authentication (not API keys).
 * The signature sheet is generated by auth.js middleware and forwarded
 * from the MCP session context on each loopback call.
 *
 * Set CASS_DEBUG=true to log all requests and responses to stderr.
 */

const CASS_URL = (process.env.CASS_URL || 'http://localhost/api').replace(/\/+$/, '');
const DEBUG = process.env.CASS_DEBUG === 'true';

/** Max characters of response body to show in debug output. */
const DEBUG_BODY_PREVIEW = parseInt(process.env.CASS_DEBUG_BODY_LENGTH || '500', 10);

/**
 * Write a debug message to stderr (safe for MCP stdio transport).
 * @param  {...any} args
 */
function debug(...args) {
    if (DEBUG) console.error('[cass-mcp:http]', ...args);
}

/**
 * Build the fully-resolved fetch URL and options from tool arguments.
 *
 * Exported separately so URL construction and parameter handling
 * can be unit-tested without making network calls.
 *
 * @param {string} method          - HTTP method (GET, POST, etc.)
 * @param {string} pathTemplate    - URL path template, e.g. "/api/data/{type}/{uid}"
 * @param {Object} args            - Flat object of all tool arguments
 * @param {Object} parameterMap    - Map from param name → { location, schema, required }
 * @param {Object} [options]       - Optional overrides
 * @param {string} [options.baseUrl]        - Override CASS_URL
 * @param {string} [options.signatureSheet] - Signature sheet JSON string from auth.js
 * @returns {{ url: string, fetchOptions: Object }}
 */
export function buildRequest(method, pathTemplate, args, parameterMap, options = {}) {
    const baseUrl = (options.baseUrl || CASS_URL).replace(/\/+$/, '');

    let resolvedPath = pathTemplate;
    const queryParams = new URLSearchParams();
    const headers = {
        'Accept': 'application/json',
    };

    // Forward the signature sheet if available.
    // kbac.js reads this from req.headers.signatureSheet.
    if (options.signatureSheet) {
        headers['signatureSheet'] = options.signatureSheet;
    }

    for (const [paramName, paramMeta] of Object.entries(parameterMap)) {
        const value = args[paramName];
        if (value === undefined || value === null) continue;

        switch (paramMeta.location) {
        case 'path':
            resolvedPath = resolvedPath.replace(`{${paramName}}`, encodeURIComponent(String(value)));
            break;
        case 'query':
            if (Array.isArray(value)) {
                for (const v of value) {
                    queryParams.append(paramName, String(v));
                }
            } else {
                queryParams.set(paramName, String(value));
            }
            break;
        case 'header':
            headers[paramName] = String(value);
            break;
        default:
            break;
        }
    }

    // The 'body' key, if present, is for requestBody content.
    let fetchBody = undefined;
    if (args.body !== undefined && args.body !== null) {
        headers['Content-Type'] = 'application/json';
        fetchBody = typeof args.body === 'string' ? args.body : JSON.stringify(args.body);
    }

    // Build the full URL.
    // The pathTemplate starts with /api/…, and baseUrl ends with /api.
    // Strip the /api prefix from the pathTemplate to avoid duplication.
    let relativePath = resolvedPath;
    if (relativePath.startsWith('/api')) {
        relativePath = relativePath.substring(4);
    }

    let url = baseUrl + relativePath;
    const qs = queryParams.toString();
    if (qs) {
        url += '?' + qs;
    }

    const fetchOptions = {
        method: method.toUpperCase(),
        headers,
    };
    if (fetchBody && method.toUpperCase() !== 'GET' && method.toUpperCase() !== 'HEAD') {
        fetchOptions.body = fetchBody;
    }

    return { url, fetchOptions };
}

/**
 * Execute an HTTP request against the CaSS server.
 *
 * @param {string} method          - HTTP method (GET, POST, PUT, DELETE, etc.)
 * @param {string} pathTemplate    - URL path template, e.g. "/api/data/{type}/{uid}"
 * @param {Object} args            - Flat object of all tool arguments
 * @param {Object} parameterMap    - Map from param name → { location: 'path'|'query'|'header', schema }
 * @param {Object} [options]       - Optional overrides (baseUrl, signatureSheet)
 * @returns {Promise<{status: number, body: string}>}
 */
export async function callCass(method, pathTemplate, args, parameterMap, options = {}) {
    const startTime = Date.now();
    const { url, fetchOptions } = buildRequest(method, pathTemplate, args, parameterMap, options);

    debug(`→ ${fetchOptions.method} ${url}`);
    if (DEBUG) {
        debug(`  Headers: ${JSON.stringify(fetchOptions.headers)}`);
        if (fetchOptions.body) {
            const preview = fetchOptions.body.length > DEBUG_BODY_PREVIEW
                ? fetchOptions.body.substring(0, DEBUG_BODY_PREVIEW) + `… (${fetchOptions.body.length} bytes total)`
                : fetchOptions.body;
            debug(`  Body: ${preview}`);
        }
    }

    let response;
    let responseText;
    try {
        response = await fetch(url, fetchOptions);
        responseText = await response.text();
    } catch (err) {
        const elapsed = Date.now() - startTime;
        debug(`✗ ${fetchOptions.method} ${url} — NETWORK ERROR after ${elapsed}ms: ${err.message}`);
        throw err;
    }

    const elapsed = Date.now() - startTime;
    debug(`← ${response.status} ${response.statusText} (${elapsed}ms, ${responseText.length} bytes)`);
    if (DEBUG && responseText) {
        const preview = responseText.length > DEBUG_BODY_PREVIEW
            ? responseText.substring(0, DEBUG_BODY_PREVIEW) + `… (${responseText.length} bytes total)`
            : responseText;
        debug(`  Body: ${preview}`);
    }

    return {
        status: response.status,
        body: responseText,
    };
}
